n_permute: 3000
use_resample: true
use_approximation: true
use_approximation_gene: false
approximation_type: "t"
test_type: "wilcoxon_test"
moi: "high"
data_dir: "/project/xuanyao/jiaming/Getting_started/data/frangieh/control"
description: "snake/frangieh_ifn_control/union_resample_30_qc"
cell_filter: true
filter_type: "percentage"
filter_umi_cutoff: 5000
filter_percentage: 0.01
rank: false
trt_cells_cutoff: 30
control_cells_cutoff: 30
advanced: false
approximation_threshold: 0.05
n_guides: 322
guide_or_target: "target"
