n_permute: 3000
use_resample: true
use_approximation: true
use_approximation_gene: false
approximation_type: "t"
test_type: "wilcoxon_test"
moi: "high"
data_dir: "/project/xuanyao/jiaming/Getting_started/data/papalexi"
description: "snake/papalexi_Hallmark/union_3000_t_ACAT_resample"
cell_filter: true
filter_type: "quantile"
filter_umi_cutoff: 5000
filter_percentage: 0.01
rank: false
trt_cells_cutoff: 7
control_cells_cutoff: 7
advanced: false
approximation_threshold: 0.05
n_guides: 34
use_ACAT: true
guide_or_target: "target"
